language: python
python: 
  - "2.7"
  - "2.6"

install:
  - "pip install -r requirements.txt"
  - "cd nose; wget https://pynbody.googlecode.com/files/testdata.tar.gz; tar -zxvf testdata.tar.gz; cd .."
  - python setup.py install

script: nosetests

