language: python
python: 
  - "2.7"
  
# use anaconda from continuum to avoid building numpy/scipy
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-3.5.2-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
# could test here for $TRAVIS_PYTHON_VERSION and make a python 2.6 conda environment
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib nose h5py
  - "cd nose; wget https://pynbody.googlecode.com/files/testdata_april_2013.tar.gz; tar -zxvf testdata.tar.gz; cd .."
  - python setup.py install

script: "cd nose; nosetests"

